POST http://localhost:3334/network/create/10/1 

###
POST http://localhost:3334/network/add/3/2

###
POST http://localhost:3334/network/add/3/3

###
DELETE http://localhost:3334/node/2/1 HTTP/1.1

###
delete http://localhost:3334/network/2

###
get http://localhost:3334/network/procesos/19

###
get http://localhost:3334/network/reload/3

###
get http://localhost:3334/network